import { Info } from 'lucide-react';

/**
 * Non-dismissable AI disclosure banner shown during all AI interactions.
 * Ensures users are aware they are communicating with an AI, not a human.
 */
export function AIDisclosureBanner() {
  return (
    <div className="flex items-start gap-2 rounded-md border border-blue-200 bg-blue-50 px-3 py-2 text-xs text-blue-800 dark:border-blue-800 dark:bg-blue-950/40 dark:text-blue-200">
      <Info className="mt-0.5 h-3.5 w-3.5 shrink-0" />
      <span>
        You are interacting with an AI assistant. Responses are generated by a language model and may not always be accurate.
      </span>
    </div>
  );
}
